version: "3.0"

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - DATABASE_ROOT_PASSWORD
        - WP_DB_NAME
        - WP_DB_USER
        - WP_DB_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wp-network
    restart: always
  
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress
    environment:
      - DOMAIN_NAME
      - WP_TITLE
      - WP_SUB_TITLE
      - DATABASE_HOST
      - WP_DB_NAME
      - WP_DB_USER
      - WP_DB_PASSWORD
      - WP_ADMIN_USR
      - WP_ADMIN_EMAIL
      - WP_ADMIN_PWD
      - WP_USR
      - WP_EMAIL
      - WP_PWD
    volumes:
      - wp-data:/var/www/wordpress
    networks:
      - wp-network
    depends_on:
      - mariadb
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: requirements/nginx
      args:
        - DOMAIN_NAME
    volumes:
      - wp-data:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - wp-network
    depends_on:
      - wordpress
    restart: always

networks:
  wp-network:
    driver: bridge
    name: wp-network

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/dpiza/data/db
  wp-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/dpiza/data/wp