version: "3.7"

services:

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        MARIADB_DATABASE:     ${MARIADB_DATABASE}
        MARIADB_USER:      ${MARIADB_USER}
        MARIADB_PASSWORD:      ${MARIADB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wp-network
    restart: always
  
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    environment:
      MARIADB_ROOT_HOST:     ${MARIADB_ROOT_HOST}
      MARIADB_DATABASE:      ${MARIADB_DATABASE}
      MARIADB_USER:          ${MARIADB_USER}
      MARIADB_PASSWORD:      ${MARIADB_PASSWORD}
      DOMAIN_NAME:           ${DOMAIN_NAME}
      WP_TITLE:              ${WP_TITLE}
      WP_ADMIN_USR:          ${WP_ADMIN_USR}
      WP_ADMIN_PWD:          ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:        ${WP_ADMIN_EMAIL}
      WP_USR:                ${WP_USR}
      WP_PWD:                ${WP_PWD}
      WP_EMAIL:              ${WP_EMAIL}
    volumes:
      - wp-data:/var/www/wordpress
    networks:
      - wp-network
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    volumes:
      - wp-data:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - wp-network
    depends_on:
      - wordpress
    restart: always

networks:
  wp-network:
    driver: bridge
    name: wp-network

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/dpiza/data/db
  wp-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/dpiza/data/wp